Add own logger
mobbexco/magento-2 pull request #141
Opened 2023-01-17 17:50 UTC by EMunozMobbex

2023-02-14 20:07 UTC, jlmobbex requested changes

2023-02-14 20:07 UTC, jlmobbex commented on Helper/Logger.php
> +            die;
También se debería imprimier en el `die` el mensaje del log fatal, para que sea legible en el front

2023-02-14 20:07 UTC, jlmobbex commented on Model/Logs.php
> +class Logs extends AbstractModel
Los modelos por standard se nombran en singular, para indicar que sólo responden a una instancia

2023-02-15 13:00 UTC, EMunozMobbex commented on Model/Logs.php
> +class Logs extends AbstractModel
Dejo estas correcciones pero antes de mergear revisá que se haya aplicado el cambio de nombre de los archivos de logs.php a  log.php, porque generalmente al commitear cambios no me suele tomar los cambios en nombres de archivos :/

2023-02-15 22:19 UTC, jlmobbex requested changes

2023-02-15 22:19 UTC, jlmobbex commented on Helper/Logger.php
> +        $this->log               = $logsFactory;
En este punto se sigue llamando al modelo de `Log` en plural

2023-02-17 12:46 UTC, jlmobbex approved these changes

2023-02-17 12:47 UTC, merged