Allow configuring entity UI d per provider eco 512
mobbexco/magento-2 pull request #185
Opened 2023-09-08 15:45 UTC by mobbexLuis

2023-09-08 18:26 UTC, EMunozMobbex requested changes

2023-09-11 15:03 UTC, EMunozMobbex approved these changes

2023-09-21 14:16 UTC, jlmobbex requested changes

2023-09-21 14:16 UTC, jlmobbex commented on Controller/Payment/Webhook.php
> +            $this->executeHook('mobbexWebhookReceived', false, $postData['data'], $order);
`$this->executeHook` no está definido

2023-09-21 14:16 UTC, jlmobbex commented on Helper/Mobbex.php
> +        if(!$this->config->get('multivendor') == 'active')
También puede ser unificado. Recordá que esta opción es un select y en `unified` y `active` debería funcionar. Revisar esto a fondo

2023-09-21 14:16 UTC, jlmobbex commented on Helper/Mobbex.php
> +        if(!empty($this->executeHook('mobbexGetVendorEntity', false, $item)))
Ejecutar este hook una sola vez y almacenar en variable, para no disparar todo el flujo de nuevo, que tiene que revisar todos los registros en la plataforma y reduce el performance.

2023-09-21 14:16 UTC, jlmobbex commented on Helper/Mobbex.php
>       * @return string $entity
Ahora también puede retornar `null`, hay que actualizar esta doc

2023-09-21 14:16 UTC, jlmobbex commented on Helper/Mobbex.php
> +     * Get the entity of a product
Ahora lo obtiene desde el item, no el product

2023-09-21 17:08 UTC, jlmobbex approved these changes

2023-09-21 17:11 UTC, merged