[ECO-643] Added an option to disable payment methods icons in checkout
mobbexco/magento-2 pull request #206
Opened 2023-12-18 18:31 UTC by mobbexLuis

2023-12-19 19:45 UTC, EMunozMobbex requested changes

2023-12-19 19:45 UTC, EMunozMobbex commented on Model/CustomConfigProvider.php
> +                if(!$this->config->get('show_method_icons') && $isCard || $this->config->get('show_method_icons'))
No entiendo esta comprobación, me parece que hubo un error al interpretar el ticket de la tarea 🤔  
Lo que estás haciendo acá es, evitar agregar los métodos de pago a la lista cuando estén deshabilitados los iconos, salvo que sea card, pero los métodos de pago deberían agregarse siempre. 

Lo que no debería agregarse, del lado del template es el <img> del icono (que es el valor que se pasa en la posición 'image' del payment method)

Este cambio se tiene que aplicar del lado del template, quizá pasándole ese valor de image como string vacio y checkeando luego en el template que solo se cree el img en caso de que haya contenido.

2023-12-19 19:51 UTC, mobbexLuis commented on Model/CustomConfigProvider.php
> +                if(!$this->config->get('show_method_icons') && $isCard || $this->config->get('show_method_icons'))
Perfecto. Lo corrijo
Gracias Emi!

2023-12-20 13:55 UTC, EMunozMobbex approved these changes

2023-12-26 15:28 UTC, jlmobbex requested changes

2023-12-26 15:28 UTC, jlmobbex commented on Helper/Config.php
> +        'show_method_icons'                  => 'payment/sugapay/advanced/show_method_icons',
En realidad creo que sería de tipo apariencia la opción

2024-01-02 18:55 UTC, jlmobbex approved these changes

2024-01-02 18:55 UTC, merged