[ECO-738] Fixed partial returns modify the total from order
mobbexco/magento-2 pull request #207
Opened 2023-12-19 19:00 UTC by mobbexLuis

-fix param passed to setGrandTotal()
-adds setTotalRefounded() to show its value correctly

2023-12-19 19:31 UTC, EMunozMobbex approved these changes

2023-12-22 18:55 UTC, jlmobbex requested changes

2023-12-22 18:55 UTC, jlmobbex commented on Model/OrderUpdate.php
> -        $order->setGrandTotal($totalPaid);
Si es un descuento si tiene que actualizarse el grand total, porque no son devoluciones, sino que forman parte del total a pagar.

2023-12-22 18:55 UTC, jlmobbex commented on Model/OrderUpdate.php
> +        $order->setTotalRefunded($orderTotal - $totalPaid);
Con este código también se setea como refunded cualquier descuento, si hubiera un recargo aparecería en negativo.

2023-12-22 20:38 UTC, jlmobbex requested changes
Dejo otro cambio que tendría que incluirse en esta PR. Hay que hacer que la devolución no modifique ni el total ni el estado del pedido. Quizás esto se podría hacer evistando que llegue a `updateTotals` y `updateStatus`, y modificando sólo lo necesario antes de ese punto.

2024-11-29 22:36 UTC, jlmobbex commented
Las devoluciones parciales ya no emiten webhooks de forma automática, por lo que la PR queda inválida. Está previsto que esto cambie en el próximo mes, sólo se emitirán webhooks de tipo child

2024-11-29 22:36 UTC, closed without merging