[ECO-1008] Added refunds management for selected items in creditmemo
mobbexco/magento-2 pull request #246
Opened 2024-06-25 21:53 UTC by mobbexLuis

2024-06-26 15:01 UTC, jlmobbex commented on Observer/RefundObserverBeforeSave.php
> +            // Set data based on item entity
Dejo el pequeño refactor que hicimos en conjunto:
```php
$entity = $this->helper->getEntity($item->getOrderItem());

if (isset($childEntities[$entity])) {
    $child = $childEntities[$entity];
    $childToRefund[$child['payment_id']] += $item->getRowTotal();
}
```

2024-06-27 12:30 UTC, EMunozMobbex commented on Observer/RefundObserverBeforeSave.php
> +            else (!empty($trx['childs']) && $creditmemo)
La identacion está rara en esta linea y hace que a primera vista parezca que es un else if y que la condicion que se evalua es de el mismo, no se si github lo está mostrando mal, dejo el comentario por las dudas.

2024-06-27 12:35 UTC, EMunozMobbex requested changes

2024-06-27 13:23 UTC, mobbexLuis commented on Observer/RefundObserverBeforeSave.php
> +            else (!empty($trx['childs']) && $creditmemo)
Si, virtualmente quedó como un elseif
Ahi lo explicité en el cambio para que la lectura sea mas clara, tampoco me convencía cómo había quedado

2024-06-27 13:37 UTC, EMunozMobbex commented on Observer/RefundObserverBeforeSave.php
> +            else (!empty($trx['childs']) && $creditmemo)
Jajaj si lo tuve que leer un par de veces hasta que entendi como venia la mano 😝

2024-06-27 14:26 UTC, EMunozMobbex requested changes

2024-06-27 14:26 UTC, EMunozMobbex commented on Observer/RefundObserverBeforeSave.php
> +                $childToRefund[$child['payment_id']] = isset($childToRefund[$child['payment_id']])
Se podria simplificar esta lógica de la siguiente manera:

```php
<?php
            if(!isset($childToRefund[$child['payment_id']]))
                $childToRefund[$child['payment_id']] = $item->getRowTotal();
            else
                $childToRefund[$child['payment_id']] += $item->getRowTotal();
```

Asi es mas clara su lectura

2024-06-27 14:34 UTC, EMunozMobbex requested changes

2024-06-27 14:34 UTC, EMunozMobbex commented on Observer/RefundObserverBeforeSave.php
> +            if (isset($childEntities[$entity])) {
para evitar anidaciones extra:

```php
<?php
if(!isset($childEntities[$entity]))
   continue;
```

2024-07-02 17:39 UTC, jlmobbex requested changes

2024-07-02 17:39 UTC, jlmobbex commented on Observer/RefundObserverBeforeSave.php
> +        $diff = $creditmemo->getGrandTotal() - $transactionData['checkout']['total'];
La comparación debería ser con el monto a devolver (el monto del creditmemo).

2024-07-02 17:39 UTC, jlmobbex commented on Observer/RefundObserverBeforeSave.php
> +            if (count($entities) > 1)
Esta lógica agrega varias veces el mismo entity si hay varios productos del mismo vendedor. Si es el caso termina arrojando excepción y se evita la devolución

2024-07-02 17:39 UTC, jlmobbex commented on Observer/RefundObserverBeforeSave.php
>              if ($amount <= 0 || !isset($data['checkout']['total']) || $amount > $data['checkout']['total'])
El `['checkout']['total']` es el total original. Esta validación debería ser con el total del pago `['payment']['total']`

2024-07-02 17:39 UTC, jlmobbex commented on Observer/RefundObserverBeforeSave.php
> +                $childToRefund[$child['payment_id']] += $item->getRowTotal();
Acá se sigue intentando devolver el total del item en lugar de buscar el vendedor y devolver el monto del creditmemo

2024-07-02 22:13 UTC, jlmobbex approved these changes

2024-07-02 22:15 UTC, merged