[ECO-867] Added the possibility to use a custom reference.
mobbexco/magento-2 pull request #252
Opened 2024-07-26 14:10 UTC by EMunozMobbex

2024-07-30 18:09 UTC, jlmobbex requested changes

2024-07-30 18:09 UTC, jlmobbex commented on Helper/Mobbex.php
> +            $sql = "SELECT $column FROM " . $connection->getTableName('sales_order') . " WHERE `entity_id` = $id;";
Esto es icompatible con el standard de magento (#251).

2024-07-30 18:09 UTC, jlmobbex commented on etc/adminhtml/system.xml
> +                        <label>Use a custom reference for checkout</label>
Démosle un label en español por ahora, luego hacemos las traducciones

2024-08-16 15:11 UTC, mobbexLuis approved these changes

2024-09-03 19:15 UTC, jlmobbex approved these changes

2024-09-03 19:15 UTC, merged