Mobbex Wallet
mobbexco/magento-2 pull request #49
Opened 2021-04-20 20:23 UTC by lorenopemac

# Description

Add Mobbex Wallet in the checkout when payment methods is selected. Wallet can be activated in the module admin page, and it's only available for logged users. 

# Features

- [x] Add "Activate Wallet" field in checkout section .
- [x] Add custom wallet checkout using quoteId instead of orderId .
- [x] Add JavaScript functions in webpay.js to render card's information.
- [x] Use Mobbex sdk for wallet payment.

2021-04-20 21:02 UTC, jlmobbex requested changes
Cambios necesarios.
También hay que agregar la lógica para manejar la orden en el controlador del webhook.

2021-04-21 11:47 UTC, lorenopemac commented on Helper/Mobbex.php
> +        $is_wallet_active = ((bool) ($this->config->getWalletActive()) ) && $userSession->isLoggedIn();
Esto es necesario porque en el checkout normal  se necesita informar que se usara la wallet, para que se almacene la tarjeta.

2021-04-21 12:19 UTC, jlmobbex commented on Helper/Mobbex.php
> +        $is_wallet_active = ((bool) ($this->config->getWalletActive()) ) && $userSession->isLoggedIn();
Ahí vi que están armando un segundo checkout cuando no se selecciona una tarjeta. Si ya está el que generás usando quote no es necesario volver a hacerlo. Habría que obtener la información que generas al crear el checkout con quote e iniciarlo con una función aparte que se llame initCheckout como en WC.

2021-04-21 12:22 UTC, jlmobbex commented on view/frontend/web/js/view/payment/method-renderer/webpay.js
>                  if (embed) {
Creo que esto sería más práctico si lo cambiamos por un else if, de forma que no se genere un checkout extra al terminar de ejecutar wallet.

2021-05-19 14:21 UTC, merged